### ISSUE TITLE
Hong Kong, Macao and Taiwan.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/dcw-gmt#55]
The three "states" are describe with its particular code (`HK,MO,TW`) and within China (`CN.HK, CN.MO, CN.TW`). I think that the files in `orig/AS` and `orig/AS/CN`) are exactly the same. 

I don't think that we should have repeated data. What do you think? Should be leave only one file? Which ones? 
Maybe @seisman will have something to say.

**Comment by Esteban82** [comment]
Maybe we could delete some repeated files and do some coding so both codes will work (e.g `HK` and `CN.HK`) from the same file.

**Comment by PaulWessel** [comment]
Will look at this in the afternoon after some meetings.

**Comment by PaulWessel** [comment]
For HK and MO the solution is clear: Neither are separate entities since the late 1990s and only CN.HK and CN.MO should exist (the database predates all of the 1997/99 changes).

Taiwan is a limbo case, so the practical solution of having both CN.TW and TW can continue until "Resolved".  I don't think it is worth doing anything about that duplicate TW.txt file but we should remove the other two.  Let me know if you will do this or you want me to handle it.

**Comment by Esteban82** [comment]
Ok. I will do it later.

**Comment by Esteban82** [comment]
Closed by #56
