### ISSUE TITLE
-ECN+gblack doesn't paint Taiwan

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/dcw-gmt#80]
**Description of the problem**

As shown below, `-ECN+gblack` doesn't paint Taiwan:
```
gmt coast -ECN+gblack -ECN.TW+pred -JH15c -png map
```
![map](https://user-images.githubusercontent.com/3974108/170636988-1845767e-80a6-4d5b-8e20-7bf730062a29.png)

**System information**

* Operating system:
* DCW version: 2.1.1
* GMT version (`gmt --version`): 6.4.0_a7493e9_2022.05.26

**Comment by PaulWessel** [comment]
We recently fixed TW and HK but I will let @Esteban82 comment since he was doing that work.

**Comment by Esteban82** [comment]
I think that the issue is that the special territorioes (Macao, Honk Kong and Taiwan; following the ISO convection) are NOT included in `CN.txt` as you can see below:

There are other cases. For example I had to use `-EAR,GS,FK` to plot Argentina with the Malvinas and Georgias Islands. 
And `-ENO,SJ` should be use to plot Norway with Svalbard and Jan Mayen (which I recently delete them from the `NO.txt`).

--
`gmt coast -ECN+gblack -ECN.HK,CN.MO,CN.TW+pred -JH15c -png map -RCN.MO,CN.TW`


![map](https://user-images.githubusercontent.com/17908951/170891389-31a22a33-cd4b-464a-82a7-dc468bf246ff.png)

**Comment by PaulWessel** [comment]
It is a bit funny that the three of us have some inside knowledge on this as to how our home countries seems things!

Since none of this is black and white to all, we should not make decisions on what belongs to whom (e.g., Taiwan to China, Malvinas to Argentina, etc).  So we let it be.

**Comment by Esteban82** [comment]
I also think should leave the CN.txt as it is. 
You could create a personal collection of codes with those 4 (CN,HK,MO,TW).

Maybe we could discuss is that collection (an other cases), should be included in the official dwc-collections.txt. I am inclined to say no, but I might change my mind.

**Comment by Esteban82** [comment]
Altough, I related issue I think it would be to add the Macao and Honk Kong to the CN.txt file. 

Since both territories are NOT island, then the users will get an internal line separating them when they just want to plot China. See the maps below (in the 2nd I add `-ECN+ggray`). 


`gmt coast -ECN+ggray -ECN,CN.HK,CN.MO+pred -JH15c -png map -RCN.MO,CN.HK+r0.1`

![map](https://user-images.githubusercontent.com/17908951/171026358-4526706c-56ca-48ba-b912-6aaa61ae3c13.png)
![map](https://user-images.githubusercontent.com/17908951/171026289-fac33287-eac7-470c-bfd0-596b6a22cfb1.png)
